package org.alexmond.jhelm.core;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.File;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.List;

/**
 * Represents a Chart.lock file that pins exact versions of dependencies.
 * <p>
 * The Chart.lock file is generated by {@code helm dependency update} and used by
 * {@code helm dependency build} to ensure reproducible builds.
 * <p>
 * Example Chart.lock structure:
 * <pre>
 * dependencies:
 *   - name: postgresql
 *     repository: https://charts.bitnami.com/bitnami
 *     version: 12.1.5
 *   - name: redis
 *     repository: https://charts.bitnami.com/bitnami
 *     version: 17.3.14
 * digest: sha256:1234567890abcdef...
 * generated: "2026-02-15T12:34:56.789Z"
 * </pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ChartLock {
    /**
     * List of locked dependencies with exact versions.
     */
    private List<LockDependency> dependencies;

    /**
     * SHA256 digest of the dependencies section for integrity verification.
     */
    private String digest;

    /**
     * Timestamp when this lock file was generated.
     */
    private String generated;

    /**
     * Represents a single locked dependency entry.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class LockDependency {
        /**
         * Name of the dependency chart.
         */
        private String name;

        /**
         * Exact version that was resolved (not a constraint).
         */
        private String version;

        /**
         * Repository URL where this version was found.
         */
        private String repository;
    }

    /**
     * Reads a Chart.lock file from the specified chart directory.
     *
     * @param chartDir the chart directory containing Chart.lock
     * @return the parsed ChartLock, or {@code null} if the file doesn't exist
     * @throws IOException if an error occurs reading or parsing the file
     */
    public static ChartLock fromFile(File chartDir) throws IOException {
        File lockFile = new File(chartDir, "Chart.lock");
        if (!lockFile.exists()) {
            return null;
        }

        ObjectMapper yamlMapper = new ObjectMapper(new YAMLFactory());
        return yamlMapper.readValue(lockFile, ChartLock.class);
    }

    /**
     * Writes this ChartLock to a Chart.lock file in the specified chart directory.
     *
     * @param chartDir the chart directory where Chart.lock should be written
     * @throws IOException if an error occurs writing the file
     */
    public void toFile(File chartDir) throws IOException {
        File lockFile = new File(chartDir, "Chart.lock");

        YAMLFactory yamlFactory = YAMLFactory.builder()
                .disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)
                .build();
        ObjectMapper yamlMapper = new ObjectMapper(yamlFactory);

        // Set generated timestamp if not already set
        if (generated == null) {
            generated = OffsetDateTime.now().toString();
        }

        yamlMapper.writeValue(lockFile, this);
    }
}
