package org.alexmond.jhelm.app;

import java.time.Instant;

import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.info.BuildProperties;
import org.springframework.lang.Nullable;
import org.springframework.stereotype.Component;

/**
 * Single source of truth for the jhelm build version, shared by every place the CLI
 * reports it ({@code jhelm --version} / {@code -V} and the {@code jhelm version}
 * subcommand).
 * <p>
 * The version comes from Spring Boot build-info — the {@link BuildProperties} bean,
 * backed by {@code META-INF/build-info.properties} generated by the
 * {@code spring-boot-maven-plugin} {@code build-info} goal. When build-info is
 * unavailable (an unpackaged IDE / test run without the generated resource) it falls back
 * to the jar manifest's {@code Implementation-Version}, and finally to a development
 * marker.
 */
@Component
public class VersionInfo {

	@Nullable
	private final BuildProperties buildProperties;

	@Autowired
	VersionInfo(ObjectProvider<BuildProperties> buildProperties) {
		// getIfAvailable() returns null when build-info is absent (e.g. an IntelliJ build
		// that
		// skips the Maven build-info goal) — version() then falls back, never failing.
		this(buildProperties.getIfAvailable());
	}

	/**
	 * Creates a version source from an explicit (possibly {@code null})
	 * {@link BuildProperties}. Primarily for tests; production uses the
	 * {@link ObjectProvider} constructor.
	 * @param buildProperties the build-info properties, or {@code null} when unavailable
	 */
	public VersionInfo(@Nullable BuildProperties buildProperties) {
		this.buildProperties = buildProperties;
	}

	/**
	 * Resolves the jhelm version.
	 * @return the version string (e.g. {@code "1.0.2-SNAPSHOT"}), never {@code null}
	 */
	public String version() {
		if (this.buildProperties != null) {
			String version = this.buildProperties.getVersion();
			if (version != null && !version.isBlank()) {
				return version;
			}
		}
		String manifest = getClass().getPackage().getImplementationVersion();
		return (manifest != null && !manifest.isBlank()) ? manifest : "development";
	}

	/**
	 * Reports whether the version was sourced from Spring Boot build-info (rather than
	 * the manifest/development fallback).
	 * @return {@code true} when the {@link BuildProperties} bean is present
	 */
	public boolean fromBuildInfo() {
		return this.buildProperties != null;
	}

	/**
	 * Returns the build timestamp recorded in build-info, when available.
	 * @return the build time, or {@code null} if build-info is unavailable
	 */
	@Nullable
	public Instant buildTime() {
		return (this.buildProperties != null) ? this.buildProperties.getTime() : null;
	}

}
